runtime: python27
service: gh-oauth
api_version: 1
threadsafe: true

libraries:
  - name: ssl
    version: latest

handlers:
  - url: /.*
    script: main.app

env_variables:
  OAUTH_CLIENT_ID: --client_id--
  OAUTH_CLIENT_SECRET: --client_secret--
